/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as Record_createRouteImport } from './routes/record_create'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CredentialShowRouteImport } from './routes/credentialShow'
import { Route as AboutRouteImport } from './routes/about'
import { Route as RecordShowRecordIdRouteImport } from './routes/recordShow.$recordId'
import { Route as RecentTitleRouteImport } from './routes/recent.$title'

const IndexLazyRouteImport = createFileRoute('/')()

const Record_createRoute = Record_createRouteImport.update({
  id: '/record_create',
  path: '/record_create',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CredentialShowRoute = CredentialShowRouteImport.update({
  id: '/credentialShow',
  path: '/credentialShow',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexLazyRoute = IndexLazyRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))
const RecordShowRecordIdRoute = RecordShowRecordIdRouteImport.update({
  id: '/recordShow/$recordId',
  path: '/recordShow/$recordId',
  getParentRoute: () => rootRouteImport,
} as any)
const RecentTitleRoute = RecentTitleRouteImport.update({
  id: '/recent/$title',
  path: '/recent/$title',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/about': typeof AboutRoute
  '/credentialShow': typeof CredentialShowRoute
  '/dashboard': typeof DashboardRoute
  '/record_create': typeof Record_createRoute
  '/recent/$title': typeof RecentTitleRoute
  '/recordShow/$recordId': typeof RecordShowRecordIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/about': typeof AboutRoute
  '/credentialShow': typeof CredentialShowRoute
  '/dashboard': typeof DashboardRoute
  '/record_create': typeof Record_createRoute
  '/recent/$title': typeof RecentTitleRoute
  '/recordShow/$recordId': typeof RecordShowRecordIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexLazyRoute
  '/about': typeof AboutRoute
  '/credentialShow': typeof CredentialShowRoute
  '/dashboard': typeof DashboardRoute
  '/record_create': typeof Record_createRoute
  '/recent/$title': typeof RecentTitleRoute
  '/recordShow/$recordId': typeof RecordShowRecordIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/credentialShow'
    | '/dashboard'
    | '/record_create'
    | '/recent/$title'
    | '/recordShow/$recordId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/credentialShow'
    | '/dashboard'
    | '/record_create'
    | '/recent/$title'
    | '/recordShow/$recordId'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/credentialShow'
    | '/dashboard'
    | '/record_create'
    | '/recent/$title'
    | '/recordShow/$recordId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  AboutRoute: typeof AboutRoute
  CredentialShowRoute: typeof CredentialShowRoute
  DashboardRoute: typeof DashboardRoute
  Record_createRoute: typeof Record_createRoute
  RecentTitleRoute: typeof RecentTitleRoute
  RecordShowRecordIdRoute: typeof RecordShowRecordIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/record_create': {
      id: '/record_create'
      path: '/record_create'
      fullPath: '/record_create'
      preLoaderRoute: typeof Record_createRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/credentialShow': {
      id: '/credentialShow'
      path: '/credentialShow'
      fullPath: '/credentialShow'
      preLoaderRoute: typeof CredentialShowRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recordShow/$recordId': {
      id: '/recordShow/$recordId'
      path: '/recordShow/$recordId'
      fullPath: '/recordShow/$recordId'
      preLoaderRoute: typeof RecordShowRecordIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recent/$title': {
      id: '/recent/$title'
      path: '/recent/$title'
      fullPath: '/recent/$title'
      preLoaderRoute: typeof RecentTitleRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  AboutRoute: AboutRoute,
  CredentialShowRoute: CredentialShowRoute,
  DashboardRoute: DashboardRoute,
  Record_createRoute: Record_createRoute,
  RecentTitleRoute: RecentTitleRoute,
  RecordShowRecordIdRoute: RecordShowRecordIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
